name: Scheduled ELT pipeline and dbt run

on:
  schedule:
    - cron: "0 6 1 1,7 *" # Every Jan 1 and July 1 at 6 AM UTC
  push:
    branches: [main]

jobs:
  run-elt-and-dbt:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create and activate virtual environment
        run: |
          PYTHON_PATH="/home/zachG/.pyenv/shims/python3.9"
          $PYTHON_PATH -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run ELT script
        run: |
          source venv/bin/activate
          python elt/main.py
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

      - name: Setup dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}

      - name: Run dbt models
        run: |
          source venv/bin/activate
          dbt run --project-dir elt/fars_dbt
